FROM ubuntu:15.10

RUN echo 'root:<ENTER_ROOT_PASSWD_HERE>' | chpasswd
RUN groupadd admin -g 1000 && \
    useradd -u 1000 -g admin -m -c "Admin user" admin

RUN apt-get update && \
    apt-get install -y openssh-server \
    git \
    wget \
    nmap \
    && rm -rf /var/lib/apt/lists/*

USER admin
