FROM jboss/keycloak

### add custome configurations
ADD keycloak-server.json /opt/jboss/keycloak/standalone/configuration/
ADD standalone.xml /opt/jboss/keycloak/standalone/configuration/

USER jboss
RUN /opt/jboss/keycloak/bin/add-user.sh [WILDFLY_USER] [WILDFLY_PASSWD] --silent

CMD ["/opt/jboss/keycloak/bin/standalone.sh", "-b", "0.0.0.0"]
